version: 0.2
phases:
  pre_build:
    commands:
      - "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  build:
    commands:
      - "docker build -t $APP_NAME:latest ."
      - "docker tag $APP_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest"
  post_builds:
    commands:
      - "docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest"
      - "printf '[{\"name\":\"$APP_NAME\",\"imageUri\":\"%s\"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest > imagedefinitions.json"
      - "printf '{\"ImageURI\":\"%s\"}' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest > imageDetail.json"
artifacts:
  files:
    - "image*.json"
  name: "BuildArtifact"
  discard-paths: "no"